### ISSUE TITLE
DAO bug

### ISSUE THREAD

**Issue by Nenad7955** [stepanovD/AndroidChatOverWebsocket#1]
https://github.com/stepanovD/AndroidChatOverWebsocket/blob/cf2b266a5c167b203e648de03a8d24be9b481f4c/client/app/src/main/java/com/distep/chatclient/data/db/dao/MessageDao.kt#L16

isn't this a bug?
isn't it supposed to be just "id"?

**Comment by stepanovD** [comment]
> 

Hello! Sorry for late in response. Yes, it's bug. This condition suppose separate messages to private chats and common chat. Here this condition is excess. Thanks for report bug.
